### PR TITLE
Revert "Clear SRAnipal logs on initialize"

### PR DESCRIPTION
**Pull request by benaclejames**
Reverting to refactor log deletion functionality. We should be using File.Delete and ensuring we catch any IO exceptions for the not-so-unlikely case where SRanipal Runtime still has a lock on it

### CODE REVIEW

**Comment by regzo2** [comment]
This change does not delete the logs, it clears the existing content within the stream to avoid dealing with locking apps. Are you saying you want to use File.Delete instead because it could just be changed to work with that (with the downside of not deleting the logs while SRanipal is already running)?

**Comment by VirtualMarten** [comment]
I believe the main issue is exception handling. For example what if we don't have permission to access the log files.
Because this is run on init and isn't essential to the function of the module, it'll probably be best to just catch any exceptions and log a warning.

**Comment by benaclejames** [comment]
File.Delete essentially does the same internally. Makes more sense to just use the built in functionality instead System.IO instead of re-implementing it. As for code readibility, File.Delete also makes intention far clearer

**Comment by VirtualMarten** [comment]
I think @regzo2 solution makes more sense here because we can't delete a file SRanipal currently has a lock on.

**Pull request closed without merging**
